version: '2'

networks:
  default:
    driver: bridge

services:
  db:
    image: postgres
    build:
      context: ./images/db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin

#  public:
#    build:
#      context: ./images/public/
#    ports:
#     - "8080:8080"
#    volumes:
#     - ./images/public:/public
#     - /public/node_modules

  api:
    build:
      context: ./images/api/
    networks:
      - default
    environment:
      PG_CONNECTION_STRING: postgres://admin:admin@db:5432/skematik
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
    links:
      - db
    depends_on:
      - db
    volumes:
      - ./images/api:/api
    ports:
      - "3000:3000"