
version: '2'
services:
  mongo:
    image: mongo:3.4

  public:
    build: images/public
    ports:
     - "8080:8080"
    volumes:
     - images/public:/public
     - /public/node_modules

  api:
    build: images/api
    environment:
      - MONGODB_URI=mongodb://mongo:27017/test
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - images/api:/api
      - /api/node_modules
    ports:
      - "3000:3000"